pipeline {
  agent any
  stages {
    stage('Build Crafter CMS') {
      steps {
        sh './gradlew build' 
      }
    }
    stage('Deploy Crafter CMS') {
      steps {
        sh './gradlew deploy'
      }
    }

    stage('Bundle Crafter CMS') {
      steps {
        sh './gradlew bundle'
      }
    }
  }
  
  post {
    always {
      archiveArtifacts artifacts: 'bundles/**', fingerprint: true
    }
  }
  options {
    timestamps()
  }
}
