pipeline {
  agent any
  stages {
    stage('Checkout CrafterCMS') {
      checkout scmGit(branches: [[name: '*/develop']], extensions: [], userRemoteConfigs: [[credentialsId: 'crafter-qa-ssh', url: 'git@github.com:craftercms/craftercms.git']])
      
    }
    
    stage('Update Crafter CMS') {
      steps {
        sshagent(['crafter-qa-ssh']) {
        // some block
          sh 'sed -i "s#https://github.com/craftercms#git@github.com:craftercms#g" gradle.properties'
          sh './gradlew update -PquietBuild=false -PrefreshEnv=true -PoverwriteArtifacts=true' 
        }  
      }
      
    }
    
    stage('Build Crafter CMS') {
      steps {
        sh './gradlew build -PquietBuild=false -PrefreshEnv=true -PoverwriteArtifacts=true' 
      }
    }
    stage('Deploy Crafter CMS') {
      steps {
        sh './gradlew deploy -PquietBuild=false -PrefreshEnv=true -PoverwriteArtifacts=true'
      }
    }

    stage('Bundle Crafter CMS') {
      steps {
        sh './gradlew bundle -PquietBuild=false -PrefreshEnv=true -PoverwriteArtifacts=true'
      }
    }
  }
  
  post {
    always {
      archiveArtifacts artifacts: 'bundles/**', fingerprint: true
    }
  }
  options {
    timestamps()
    skipDefaultCheckout()
  }
}
